const AIR_DATA = [
  { city: 'Atlanta', code: 'ATL' },
  { city: 'Amsterdam', code: 'AMS' },
  { city: 'Bangkok', code: 'BKK' },
  { city: 'Barcelona', code: 'BCN' },
  { city: 'Beijing', code: 'PEK' },
  { city: 'Berlin', code: 'TXL' },
  { city: 'Bogota', code: 'BOG' },
  { city: 'Boston', code: 'BOS' },
  { city: 'Brussels', code: 'BRU' },
  { city: 'Buenos Aires', code: 'EZE' },
  { city: 'Cairo', code: 'CAI' },
  { city: 'Cancun', code: 'CUN' },
  { city: 'Chicago', code: 'ORD' },
  { city: 'Copenhagen', code: 'CPH' },
  { city: 'Dallas/Fort Worth', code: 'DFW' },
  { city: 'Delhi', code: 'DEL' },
  { city: 'Denver', code: 'DEN' },
  { city: 'Dubai', code: 'DXB' },
  { city: 'Dublin', code: 'DUB' },
  { city: 'Frankfurt', code: 'FRA' },
  { city: 'Guangzhou', code: 'CAN' },
  { city: 'Hanoi', code: 'HAN' },
  { city: 'Helsinki', code: 'HEL' },
  { city: 'Ho Chi Minh City', code: 'SGN' },
  { city: 'Hong Kong', code: 'HKG' },
  { city: 'Houston', code: 'IAH' },
  { city: 'Istanbul', code: 'IST' },
  { city: 'Jakarta', code: 'CGK' },
  { city: 'Johannesburg', code: 'JNB' },
  { city: 'Kuala Lumpur', code: 'KUL' },
  { city: 'Las Vegas', code: 'LAS' },
  { city: 'London', code: 'LHR' },
  { city: 'Los Angeles', code: 'LAX' },
  { city: 'Madrid', code: 'MAD' },
  { city: 'Manila', code: 'MNL' },
  { city: 'Melbourne', code: 'MEL' },
  { city: 'Mexico City', code: 'MEX' },
  { city: 'Miami', code: 'MIA' },
  { city: 'Milan', code: 'MXP' },
  { city: 'Moscow', code: 'SVO' },
  { city: 'Mumbai', code: 'BOM' },
  { city: 'Munich', code: 'MUC' },
  { city: 'Nairobi', code: 'NBO' },
  { city: 'New York', code: 'JFK' },
  { city: 'Orlando', code: 'MCO' },
  { city: 'Osaka', code: 'KIX' },
  { city: 'Paris', code: 'CDG' },
  { city: 'Perth', code: 'PER' },
  { city: 'Philadelphia', code: 'PHL' },
  { city: 'Prague', code: 'PRG' },
  { city: 'Rio de Janeiro', code: 'GIG' },
  { city: 'Rome', code: 'FCO' },
  { city: 'San Francisco', code: 'SFO' },
  { city: 'Santiago', code: 'SCL' },
  { city: 'São Paulo', code: 'GRU' },
  { city: 'Seattle', code: 'SEA' },
  { city: 'Seoul', code: 'ICN' },
  { city: 'Shanghai', code: 'PVG' },
  { city: 'Singapore', code: 'SIN' },
  { city: 'Stockholm', code: 'ARN' },
  { city: 'Sydney', code: 'SYD' },
  { city: 'Taipei', code: 'TPE' },
  { city: 'Tokyo', code: 'NRT' },
  { city: 'Toronto', code: 'YYZ' },
  { city: 'Vancouver', code: 'YVR' },
  { city: 'Venice', code: 'VCE' },
  { city: 'Vienna', code: 'VIE' },
  { city: 'Warsaw', code: 'WAW' },
  { city: 'Washington D.C.', code: 'IAD' },
  { city: 'Zurich', code: 'ZRH' }
]




export default AIR_DATA